agent_name: bigfootgolf-agent
auth:
    aws_profile_env: AWS_PROFILE
    github_token_env: GITHUB_TOKEN
aws:
    ecs:
        cluster_name: bigfootgolf-cluster
        create_efs: false
        create_secrets: true
        database_cpu: 256
        database_http_port: 7474
        database_memory: 512
        database_port: 7687
        efs_volume_id: ""
        environment:
            env: production
            port: "8000"
        load_balancer_name: bigfootgolf-alb
        mode: prod
        security_group_ids: []
        service_name: bigfootgolf-service-v3
        subnet_ids: []
        task_definition_name: bigfootgolf-task-v3
        vpc_id: ""
        webapp_cpu: 256
        webapp_memory: 512
        webapp_port: 8000
    lightsail:
        container_name: bigfootgolf-app
        environment:
            env: production
            port: "8000"
        power: nano
        public_domain: bigfootgolf.example.com
        scale: 1
        service_name: bigfootgolf-service
    region: us-east-1
claude:
    max_tokens: 4096
    model_id: anthropic.claude-3-sonnet-20240229-v1:0
    region: us-east-1
    temperature: 0.1
images:
    app_image: ghcr.io/jrzesz33/bigfootgolf-webapp:sha-788e856
    neo4j_image: ghcr.io/jrzesz33/bigfootgolf-db:sha-9270da4
    registry: docker.io
log_level: info
port: 8080
