agent_name: bigfootgolf-agent
auth:
    github_token_env: GITHUB_TOKEN
aws:
    lightsail:
        container_name: bigfootgolf-app
        environment:
            env: production
            port: "8080"
        power: nano
        public_domain: bigfootgolf.example.com
        scale: 1
        service_name: bigfootgolf-service
    region: us-east-1
build:
    app_name: bigfootgolf
    output_dir: ./build
claude:
    max_tokens: 4096
    model_id: anthropic.claude-3-sonnet-20240229-v1:0
    region: us-east-1
    temperature: 0.1
git:
    branch: main
    repository: https://github.com/jrzesz33/bigfootgolf
    working_dir: ./tmp
log_level: info
port: 8080
